#!/bin/bash
set -euo pipefail

# ─────────────────────────────────────────────────────────────────
# update.sh — upgrade the AI CLI stack to the latest releases, safely.
#
#   1. Check the currently-installed Claude Code version.
#   2. Snapshot config into backup/YYYYMMDD_HHMMSS/ with a generated
#      rollback.sh, so any upgrade can be reverted.
#   3. Upgrade Claude Code to latest (native `claude update`, or npm
#      if that's how it was installed).
#   4. Upgrade the sibling agent CLIs when present — codex,
#      cursor-agent, cortex, opencode, gemini, pi, grok, headroom
#      (scripts/agents-update.sh, the same script ansible-ai/update.yml
#      runs on the fleet; also reports 9router gateway status).
#   5. Re-vendor the 9router skills from upstream and deploy them to
#      ~/.claude/skills (scripts/vendor-9router-skills.sh --deploy).
#   6. Prune old backups (last 7 days + first-of-month snapshots).
#   7. With --all: propagate to the fleet servers via
#      ansible-ai/update.yml --limit aorus_ai (this machine was already
#      updated by steps 1-6, so the playbook skips it).
#
# Flags:
#   --all          After the local update, run the fleet playbook so every
#                  server gets the same treatment. Requires ansible + an
#                  inventory (ansible-ai/inventory.local.yml). Note: servers
#                  pull from origin/main — use ./deploy.sh to publish config
#                  changes first.
#   --dry-run      Take the backup, but DON'T upgrade. Previews the Claude
#                  step only — sibling CLIs, 9router skills, prune, and
#                  fleet are all skipped.
#   --claude-only  Skip the sibling agent CLIs and 9router skills (4-5).
#   --no-prune     Skip the post-upgrade backup prune.
# ─────────────────────────────────────────────────────────────────

# ── Colors & helpers ─────────────────────────────────────────────
BOLD='\033[1m'; DIM='\033[2m'; GREEN='\033[32m'; YELLOW='\033[33m'
RED='\033[31m'; CYAN='\033[36m'; RESET='\033[0m'
ok()     { echo -e "  ${GREEN}✓${RESET} $1"; }
skip()   { echo -e "  ${DIM}○ $1${RESET}"; }
warn()   { echo -e "  ${YELLOW}!${RESET} $1"; }
fail()   { echo -e "  ${RED}✗${RESET} $1"; }
header() { echo -e "\n${BOLD}$1${RESET}"; }

DOTFILES_DIR="$(cd "$(dirname "$0")" && pwd)"
CLAUDE_DIR="$HOME/.claude"
CLAUDE_JSON="$HOME/.claude.json"
BACKUP_ROOT="$DOTFILES_DIR/backup"
TS="$(date +%Y%m%d_%H%M%S)"

DRY_RUN="no"; RUN_PRUNE="yes"; RUN_AGENTS="yes"; RUN_FLEET="no"
for arg in "$@"; do
  case "$arg" in
    --all)         RUN_FLEET="yes" ;;
    --dry-run)     DRY_RUN="yes" ;;
    --claude-only) RUN_AGENTS="no" ;;
    --no-prune)    RUN_PRUNE="no" ;;
    -h|--help)
      echo "Usage: ./update.sh [--all] [--dry-run] [--claude-only] [--no-prune]"
      echo "  Backs up config to backup/<timestamp>/ then upgrades Claude Code"
      echo "  and the sibling agent CLIs (codex, cursor-agent, cortex, opencode, gemini, pi, grok, headroom)."
      echo "  --all also runs ansible-ai/update.yml against the fleet servers afterward."
      exit 0 ;;
    *) warn "Unknown flag: $arg (ignored)" ;;
  esac
done

SUDO=""
[ "$(id -u)" -ne 0 ] && command -v sudo &>/dev/null && SUDO="sudo"

# ── Locate Claude Code & determine how it was installed ──────────
if ! command -v claude &>/dev/null; then
  fail "Claude Code isn't installed. Run ./setup.sh first."
  exit 1
fi

CLAUDE_BIN="$(command -v claude)"
CURRENT_VERSION="$(claude --version 2>/dev/null | awk '{print $1}')"

INSTALL_METHOD="native"
CLAUDE_BIN_TARGET=""
if npm ls -g @anthropic-ai/claude-code &>/dev/null; then
  INSTALL_METHOD="npm"
elif [ -L "$CLAUDE_BIN" ]; then
  CLAUDE_BIN_TARGET="$(readlink -f "$CLAUDE_BIN" 2>/dev/null || true)"
fi

header "Claude Code Update"
ok "Installed version: ${CURRENT_VERSION:-unknown}"
ok "Install method:    $INSTALL_METHOD${CLAUDE_BIN_TARGET:+  (→ $CLAUDE_BIN_TARGET)}"

# ── 1. Backup ────────────────────────────────────────────────────
BACKUP_DIR="$BACKUP_ROOT/$TS"
CFG_DIR="$BACKUP_DIR/claude-config"
mkdir -p "$CFG_DIR"

# Copy the config that an upgrade could migrate/break. -L dereferences
# symlinks so the backup holds real files (e.g. a symlinked settings.json).
copy_if_present() {
  local src="$1" dst="$2"
  [ -e "$src" ] || return 0
  cp -L "$src" "$dst" 2>/dev/null && return 0
  cp "$src" "$dst" 2>/dev/null || true
}
copy_if_present "$CLAUDE_DIR/settings.json"       "$CFG_DIR/settings.json"
copy_if_present "$CLAUDE_DIR/settings.local.json" "$CFG_DIR/settings.local.json"
copy_if_present "$CLAUDE_DIR/CLAUDE.md"           "$CFG_DIR/CLAUDE.md"
copy_if_present "$CLAUDE_JSON"                     "$CFG_DIR/claude.json"

HAS_SETTINGS_LOCAL="no"; [ -f "$CFG_DIR/settings.local.json" ] && HAS_SETTINGS_LOCAL="yes"

# Machine-readable manifest that rollback.sh sources.
cat > "$BACKUP_DIR/manifest.env" <<EOF
# Auto-generated by update.sh — do not edit.
CLAUDE_VERSION_BEFORE="${CURRENT_VERSION}"
INSTALL_METHOD="${INSTALL_METHOD}"
CLAUDE_BIN="${CLAUDE_BIN}"
CLAUDE_BIN_TARGET="${CLAUDE_BIN_TARGET}"
DEST_SETTINGS="${CLAUDE_DIR}/settings.json"
DEST_SETTINGS_LOCAL="${CLAUDE_DIR}/settings.local.json"
HAS_SETTINGS_LOCAL="${HAS_SETTINGS_LOCAL}"
DEST_CLAUDE_MD="${CLAUDE_DIR}/CLAUDE.md"
DEST_CLAUDE_JSON="${CLAUDE_JSON}"
EOF

# Static rollback script — reads manifest.env for the concrete paths.
cat > "$BACKUP_DIR/rollback.sh" <<'ROLLBACK'
#!/bin/bash
# Restore the config snapshot in this folder and revert Claude Code to the
# version that was installed before the corresponding update.sh run.
set -euo pipefail
HERE="$(cd "$(dirname "$0")" && pwd)"
. "$HERE/manifest.env"
cfg="$HERE/claude-config"

echo "Rolling back Claude Code to ${CLAUDE_VERSION_BEFORE:-previous}..."

[ -f "$cfg/settings.json" ]       && cp "$cfg/settings.json"       "$DEST_SETTINGS"       && echo "  restored settings.json"
[ "$HAS_SETTINGS_LOCAL" = "yes" ] && cp "$cfg/settings.local.json" "$DEST_SETTINGS_LOCAL" && echo "  restored settings.local.json"
[ -f "$cfg/CLAUDE.md" ]           && cp "$cfg/CLAUDE.md"           "$DEST_CLAUDE_MD"       && echo "  restored CLAUDE.md"
[ -f "$cfg/claude.json" ]         && cp "$cfg/claude.json"         "$DEST_CLAUDE_JSON"     && echo "  restored ~/.claude.json"

if [ "$INSTALL_METHOD" = "native" ] && [ -n "$CLAUDE_BIN_TARGET" ] && [ -e "$CLAUDE_BIN_TARGET" ]; then
  ln -sfn "$CLAUDE_BIN_TARGET" "$CLAUDE_BIN"
  echo "  re-pointed claude -> $CLAUDE_BIN_TARGET"
elif [ "$INSTALL_METHOD" = "native" ]; then
  echo "  ! previous binary ($CLAUDE_BIN_TARGET) is gone — reinstall with:"
  echo "      claude install ${CLAUDE_VERSION_BEFORE}"
else
  echo "  npm install: revert with:"
  echo "      npm install -g @anthropic-ai/claude-code@${CLAUDE_VERSION_BEFORE}"
fi

echo "Rollback complete. Restart Claude Code."
ROLLBACK
chmod +x "$BACKUP_DIR/rollback.sh"

ok "Backup: backup/$TS/  ${DIM}(config + rollback.sh)${RESET}"

# ── 2. Upgrade ───────────────────────────────────────────────────
if [ "$DRY_RUN" = "yes" ]; then
  header "Dry run"
  if [ "$INSTALL_METHOD" = "npm" ]; then
    skip "Would run: ${SUDO:+sudo }npm install -g @anthropic-ai/claude-code@latest"
  else
    skip "Would run: claude update"
  fi
  [ "$RUN_FLEET" = "yes" ] && skip "Would run: ansible-playbook update.yml --limit aorus_ai  (fleet servers)"
  ok "Backup created; no upgrade performed."
  exit 0
fi

header "Upgrading"
if [ "$INSTALL_METHOD" = "npm" ]; then
  npm install -g @anthropic-ai/claude-code@latest \
    || $SUDO npm install -g @anthropic-ai/claude-code@latest \
    || { fail "npm upgrade failed"; exit 1; }
else
  claude update || { fail "claude update failed"; exit 1; }
fi

NEW_VERSION="$(claude --version 2>/dev/null | awk '{print $1}')"

if [ "$NEW_VERSION" = "$CURRENT_VERSION" ]; then
  ok "Already on the latest version (${NEW_VERSION})."
else
  ok "Upgraded: ${CURRENT_VERSION} → ${GREEN}${NEW_VERSION}${RESET}"
  echo -e "  ${DIM}Restart Claude Code to load the new version.${RESET}"
fi
echo -e "  ${DIM}Roll back anytime:  ${CYAN}backup/$TS/rollback.sh${RESET}"

# ── 3. Sibling agent CLIs ────────────────────────────────────────
if [ "$RUN_AGENTS" = "yes" ] && [ -x "$DOTFILES_DIR/scripts/agents-update.sh" ]; then
  echo
  "$DOTFILES_DIR/scripts/agents-update.sh" || warn "Some agent CLI upgrades failed (non-fatal)."
fi

# ── 3b. herdr (firstmate session backend, macOS/brew only) ───────
# Local-only by design: this lives in update.sh (control-node orchestrator),
# NOT agents-update.sh — so the ansible fleet never upgrades it. The Mac
# control nodes that run firstmate keep it current; the Linux aorus hosts
# never see it. brew-gated, so it also no-ops on a non-brew mac.
if [ "$RUN_AGENTS" = "yes" ] && command -v brew &>/dev/null && command -v herdr &>/dev/null; then
  header "herdr (firstmate backend)"
  before_herdr="$(herdr --version 2>/dev/null | awk '{print $NF}')"
  if brew upgrade herdr >/dev/null 2>&1; then
    after_herdr="$(herdr --version 2>/dev/null | awk '{print $NF}')"
    [ "$before_herdr" = "$after_herdr" ] && ok "herdr: already latest (${after_herdr})" \
      || ok "herdr: ${before_herdr} → ${after_herdr}"
  else
    ok "herdr: already latest (${before_herdr})"
  fi
fi

# ── 4. 9router skills (vendored from decolua/9router) ────────────
# Re-vendors the skill set from upstream and deploys it to
# ~/.claude/skills. Writes into the repo's skills/ dir, so changes
# still need a commit + push before the fleet sees them.
if [ "$RUN_AGENTS" = "yes" ] && [ -x "$DOTFILES_DIR/scripts/vendor-9router-skills.sh" ]; then
  header "9router skills"
  if ! command -v gh &>/dev/null; then
    skip "gh CLI not available — skills not re-vendored"
  elif "$DOTFILES_DIR/scripts/vendor-9router-skills.sh" --deploy >/dev/null 2>&1; then
    if git -C "$DOTFILES_DIR" status --porcelain -- skills/9router\* 2>/dev/null | grep -q .; then
      ok "Re-vendored from decolua/9router → ~/.claude/skills"
      warn "skills/ has uncommitted changes — commit + push so the fleet picks them up"
    else
      ok "Already current (deployed to ~/.claude/skills)"
    fi
  else
    warn "9router skills re-vendor failed (non-fatal — check gh auth / network)"
  fi
fi

# ── 5. Prune old backups ─────────────────────────────────────────
if [ "$RUN_PRUNE" = "yes" ] && [ -x "$DOTFILES_DIR/scripts/backup-prune.sh" ]; then
  echo
  "$DOTFILES_DIR/scripts/backup-prune.sh" || warn "Backup prune had issues (non-fatal)."
fi

# ── 6. Fleet propagation (--all) ─────────────────────────────────
# Servers only (--limit aorus_ai): this machine was already updated above,
# and update.yml's local play would redo the same work. Servers pull the
# repo from origin/main — publish config changes with ./deploy.sh first.
if [ "$RUN_FLEET" = "yes" ]; then
  header "Fleet update (ansible-ai/update.yml --limit aorus_ai)"
  INV="$DOTFILES_DIR/ansible-ai/inventory.local.yml"
  if ! command -v ansible-playbook &>/dev/null; then
    fail "ansible-playbook not found — install ansible, or run this from the control node."
    exit 1
  elif [ ! -f "$INV" ]; then
    fail "No inventory at ansible-ai/inventory.local.yml"
    echo -e "  ${DIM}Bootstrap it:  cp ansible-ai/inventory.example.yml ansible-ai/inventory.local.yml${RESET}"
    exit 1
  fi
  if (cd "$DOTFILES_DIR/ansible-ai" && ansible-playbook update.yml --limit aorus_ai); then
    ok "Fleet servers updated."
  else
    warn "Fleet update finished with failures — offline hosts are skipped; check the recap above."
  fi
fi
